'use client'; // This directive marks the component as a Client Component

import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import Navmenu from '@/components/navbar/Navmenu';
import TopNav from '@/components/navbar/topNav';
import Footer from '@/components/footer/page';
import EnquiryForm from '@/components/EnquiryForm/EnquiryForm';
import { useState } from 'react';
import ContactUsHomeBtn from '@/components/ContactUsHomeBtn/ContactUsHomeBtn';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [enquiryModal, setEnquiryModal] = useState(false);

  return (
    <html lang="en">
      <body className={`relative ${inter.className}`}>
        <div>
          <TopNav />
          <Navbar setEnquiryModal={setEnquiryModal} />
          <Navmenu />
          {children}
          {enquiryModal && <EnquiryForm setEnquiryModal={setEnquiryModal} />}
          <Footer />
        </div>
        <div className='fixed top-[76%] -right-[58px] -rotate-90'>
          <ContactUsHomeBtn/>
        </div>
      </body>
    </html>
  );
}
